config/routes.rb
# DON'T FORGET - If you make a change to this file, you HAVE to restart the rails
# server UNLESS you are running in the development environment.
Rails.application.routes.draw do

  resources :topics, only: [:index, :show]

  # Our custom routes for devise
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'coldfusion-items', to: 'portfolios#coldfusion', as: 'coldfusion_items'
  get 'ruby-on-rails-items', to: 'portfolios#ruby_on_rails', as: 'ruby_on_rails_items'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html

  get 'about-me', to: 'pages#about', as: 'about_me'
  get 'contact', to: 'pages#contact'
  get 'cred', to: 'pages#credentials', as: 'creds'
  get 'tech-news', to: 'pages#tech_news', as: 'tech_news'

  # Set up routes for comments websocket
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body, :topic_id

  belongs_to :topic

  has_many :comments, dependent: :destroy

  def self.special_blogs
    all
  end

  def self.featured_blogs
    limit(2)
  end

  def self.recent
    order('created_at DESC')
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy toggle_status]
  before_action :set_sidebar_topics, except: [:update, :create, :destroy, :toggle_status]
  layout 'blog'  # Maps directly to the file in the layouts directory.
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs or /blogs.json
  def index
    if logged_in?(:site_admin)
      @blogs = Blog.recent.page(params[:page]).per(5)
    else
      @blogs = Blog.published.recent.page(params[:page]).per(5)
    end
    @page_title = 'JohnArnold.net Blog'
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    if logged_in?(:site_admin) || @blog.published?
      @blog = Blog.includes(:comments).friendly.find(params[:id])
      @comment = Comment.new  # Used in form on the blog show page.
      @page_title = @blog.title
      @seo_keywords = @blog.body
    else
      redirect_to blogs_path, notice: 'You are not authorized to view this page.'
    end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit; end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: 'Blog was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
    end
  end

  def toggle_status
    if @blog.published?
      @blog.draft!
    else
      @blog.published!
    end
    redirect_to blogs_url, notice: 'Post status updated'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    # Change this to use friendly ids
    # @blog = Blog.find(params[:id])
    @blog = Blog.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def blog_params
    params.require(:blog).permit(:title, :body, :topic_id, :status)
  end

  def set_sidebar_topics
    @sidebar_topics = Topic.with_blogs
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar_helper(user)
    image_tag "https://gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 40
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)
    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      auto_link: true,
      lax_html_blocks: true
    }
    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/views/blogs/_admin_actions.html.erb
<% if logged_in?(:site_admin) %>
  <nav class="breadcrumb row blog-crumb">
    <div class="col">
      <%= link_to fa_icon('file-text'), toggle_status_blog_path(blog), class: "#{blog.status}" %>
      <%= link_to fa_icon('pencil-square-o'), edit_blog_path(blog) %>
      <%= link_to fa_icon('trash'), blog, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </nav>
<% end %>

app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to blog.title.upcase, blog_path(blog) %></h2>
  <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>
  <%= render partial: 'blogs/admin_actions', locals: { blog: blog } %>
  <p><%= blog.body %></p>
</div>

app/views/blogs/_form.html.erb
<div class="card">
  <div class="card-body">
    <%= form_with(model: blog, local: true) do |form| %>

      <% if blog.errors.any? %>
        <% blog.errors.full_messages.each do |e| %>
          <%= alert_generator e %>
        <% end %>
      <% end %>

      <div class="form-group">
        <%= form.text_field :title, class: 'form-control', placeholder: 'Title' %>
      </div>

      <div class="form-group">
        <%= form.label :topic %>
        <%= form.select :topic_id,
                        options_from_collection_for_select(Topic.all, 'id', 'title', @blog.topic_id),
                        { selected: blog.topic.id, include_blank: true },
                        {class: "form-control"}
        %>
      </div>

      <div class="form-group">
        <%= form.radio_button :status, 'draft' %>
        <%= form.label :status, 'Draft' %>
        <%= form.radio_button :status, 'published' %>
        <%= form.label :status, 'Published' %>
      </div>

      <div class="form-group">
        <%= form.text_area :body, class: 'form-control', rows: 15, placeholder: 'Content' %>
      </div>

      <div class="actions">
        <%= form.submit "Submit", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/blogs/edit.html.erb
<div class="col-md-8 blog-main">
  <h3>Edit Blog</h3>
  <%= render 'form', blog: @blog %>
  <%= link_to 'View this blog', @blog %>
</div>

app/views/blogs/index.html.erb
<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
  <div class="col-md-6 px-0">
    <h1 class="display-4 font-italic">Title of a longer featured blog post</h1>
    <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what's most interesting in this post's contents.</p>
    <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>
  </div>
</div>

<div class="col-md-6">
  <div class="card flex-md-row mb-4 shadow-sm h-md-250">
    <div class="card-body d-flex flex-column align-items-start">
      <strong class="d-inline-block mb-2 text-primary">World</strong>
      <h3 class="mb-0">
        <a class="text-dark" href="#">Featured post</a>
      </h3>
      <div class="mb-1 text-muted">Nov 12</div>
      <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
      <a href="#">Continue reading</a>
    </div>
    <img class="card-img-right flex-auto d-none d-lg-block" data-src="holder.js/200x250?theme=thumb" alt="Card image cap">
  </div>
</div>
<div class="col-md-6">
  <div class="card flex-md-row mb-4 shadow-sm h-md-250">
    <div class="card-body d-flex flex-column align-items-start">
      <strong class="d-inline-block mb-2 text-success">Design</strong>
      <h3 class="mb-0">
        <a class="text-dark" href="#">Post title</a>
      </h3>
      <div class="mb-1 text-muted">Nov 11</div>
      <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
      <a href="#">Continue reading</a>
    </div>
    <img class="card-img-right flex-auto d-none d-lg-block" data-src="holder.js/200x250?theme=thumb" alt="Card image cap">
  </div>
</div>

<div class="col-md-8 blog-main">
  <p id="notice"><%= notice %></p>
  <h3 class="pb-3 mb-4 font-italic border-bottom">From the Firehose</h3>
  <%= render @blogs %>

  <%= paginate @blogs %>
</div>

app/views/blogs/new.html.erb
<div class="col-md-8 blog-main">
  <h3>New Blog</h3>
  <%= render 'form', blog: @blog %>
  <div>
    <%= link_to 'Back', blogs_path %>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="col-md-8 blog-main">
  <h3><%= @blog.title %></h3>

  <nav class="breadcrumb row">
    <div class="col">
      <%= link_to 'Home', root_path, class: 'breadcrumb-item' %>
      <%= link_to @blog.topic.title, topic_path(@blog.topic), class: 'breadcrumb-item' %>
      <span class="breadcrumb-item active" aria-current="page"><%= @blog.title %></span>
      <span class="float-right">
        <%= link_to fa_icon('pencil-square-o'), edit_blog_path(@blog) if logged_in?(:site_admin) %>
        <%= link_to fa_icon('trash'), @blog, method: :delete, data: { confirm: 'Really delete this, Sparky?' } if logged_in?(:site_admin) %>
      </span>
    </div>
  </nav>

  <h4><%= @blog.topic.title %></h4>
  <p><%= @blog.status.upcase if logged_in?(:site_admin) %></p>
  <p><%= markdown(@blog.body) %></p>

  <%= render 'comments/comment_form' %>
  <div id="comments" data-blog-id="<%= @blog.id %>">
    <%= render @blog.comments %>
  </div>

</div>