config/routes.rb
# DON'T FORGET - If you make a change to this file, you HAVE to restart the rails
# server UNLESS you are running in the development environment.
Rails.application.routes.draw do

  resources :topics, only: [:index, :show]

  # Our custom routes for devise
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'coldfusion-items', to: 'portfolios#coldfusion', as: 'coldfusion_items'
  get 'ruby-on-rails-items', to: 'portfolios#ruby_on_rails', as: 'ruby_on_rails_items'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html

  get 'about-me', to: 'pages#about', as: 'about_me'
  get 'contact', to: 'pages#contact'
  get 'cred', to: 'pages#credentials', as: 'creds'
  get 'tech-news', to: 'pages#tech_news', as: 'tech_news'

  # Set up routes for comments websocket
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  # Create a custom scope using a class method - The preferred way since it looks more like ruby
  def self.coldfusion
    where(subtitle: 'ColdFusion')
  end

  # Custom scope using lambda notation - not as clear, i think.
  # scope :ruby_on_rails, -> { where(subtitle: 'Ruby on Rails') }
  def self.ruby_on_rails
    where(subtitle: 'Ruby on Rails')
  end

  def self.by_position
    order("position ASC")
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: %i[show edit update destroy]
  layout 'portfolio'
  access all: [:show, :index, :coldfusion, :ruby_on_rails], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
    head :ok #bypasses the normal rails pipeline so it doesn't look for a sort template
  end

  def coldfusion
    @cf_portfolio_items = Portfolio.coldfusion  # uses a custom scope in the model defined as a class method
  end

  def ruby_on_rails
    @ruby_portfolio_items = Portfolio.ruby_on_rails  # uses a custom scope in the model defined as a scope
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'New portfolio item is now live' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  # PATCH/PUT /portfolios/1 or /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio item updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'The record has been removed.' }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow white listed parameters through/
  # This is how the routing engine controls what is allowed to be passed from the form to the
  # controller.
  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :main_image,
                                      :thumb_image,
                                      :body,
                                      technologies_attributes: [:id, :name, :_destroy]  # the _destroy is a cocoon attr
                                      )
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "https://place-hold.it/#{height}x#{width}"
  end

  def portfolio_img(img, type)
    if img.file
      img.to_s
    elsif type == 'thumb'
      image_generator(height: '300', width: '200')
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end

end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |form| %>

  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |e| %>
      <%= alert_generator e %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-12 col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label class="btn btn-primary btn-block">
          Main image file <%= form.file_field :main_image, style: 'display:none' %>
        </label>
      </div>
      <div class="form-group">
        <label class="btn btn-primary btn-block">
          Thumb image file <%= form.file_field :thumb_image, style: 'display:none' %>
        </label>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: 'form-control', rows: 10 %>
      </div>
    </div>
    <div class="col-12">
      <h3>Technologies used:</h3>
      <div>
        <%= form.fields_for :technologies do |technology_form| %>
          <%= render 'technology_fields', f: technology_form %>
        <% end %>
        <div>
          <%= link_to_add_association 'Add Technology', form, :technologies %>
        </div>
      </div>
      <div>
        <%= form.submit 'Submit', class: 'btn btn-primary btn-block' %>
      </div>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4 card-wrapper" data-id="<%= portfolio_item.id %>">
  <div class="card mb-4 shadow-sm">
    <%= image_tag portfolio_img(portfolio_item.thumb_image, 'thumb') , class: 'card-img-top' unless portfolio_item.thumb_image.nil? %>
    <div class="card-body">
      <p class="card-text">
        <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span>
        <%= portfolio_item.subtitle %>
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
        </div>
        <small class="text-muted"><%= distance_of_time_in_words(portfolio_item.created_at, Time.now) %></small>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove', f %>
</div>

app/views/portfolios/coldfusion.html.erb
<h1>Coldfusion Portfolio Items</h1>
<p style="color: green"><%= notice %></p>
<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>

<% @cf_portfolio_items.each do |portfolio_item| %>
  <h2><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></h2>
  <h3><%= portfolio_item.subtitle %></h3>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %> |
  <%= link_to 'Delete Porfolio Item', portfolio_item, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
<% end %>

<script>
    console.log("On Portfolios View");
</script>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">
  <h2>Edit Portfolio Item</h2>
  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <%= source_helper('alert alert-warning') %>
    <div class="row <%= 'sortable' if logged_in?(:site_admin) %>" >
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
  <h2>Create a new Portfolio Item</h2>
  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/ruby_on_rails.html.erb
<h1>Ruby on Rails Portfolio Items</h1>
<p style="color: green"><%= notice %></p>
<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>

<% @ruby_portfolio_items.each do |portfolio_item| %>
  <h2><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></h2>
  <h3><%= portfolio_item.subtitle %></h3>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %> |
  <%= link_to 'Delete Porfolio Item', portfolio_item, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
<% end %>

<script>
    console.log("On Portfolios View");
</script>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-12 col-md-7">
      <div><%= image_tag portfolio_img(@portfolio_item.main_image, 'main'), class: 'img-portfolio' %></div>
    </div>
    <div class="col-12 col-md-5">
      <h2><%= @portfolio_item.title %></h2>
      <em><%= @portfolio_item.subtitle %></em>
      <p><%= @portfolio_item.body %></p>
      <h4>Technologies used:</h4>
      <ul>
        <% @portfolio_item.technologies.each do |t| %>
          <li><%= t.name %></li>
        <% end %>
      </ul>
      <% if logged_in?(:site_admin) %>
        <div>
          <%= link_to 'Edit item', edit_portfolio_path, class: 'btn btn-warning' %>
        </div>
      <% end %>
    </div>
  </div>
</div>