config/routes.rb
# DON'T FORGET - If you make a change to this file, you HAVE to restart the rails
# server UNLESS you are running in the development environment.
Rails.application.routes.draw do

  resources :topics, only: [:index, :show]

  # Our custom routes for devise
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'coldfusion-items', to: 'portfolios#coldfusion', as: 'coldfusion_items'
  get 'ruby-on-rails-items', to: 'portfolios#ruby_on_rails', as: 'ruby_on_rails_items'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  # For details on the DSL available within this file, see
  # http://guides.rubyonrails.org/routing.html

  get 'about-me', to: 'pages#about', as: 'about_me'
  get 'contact', to: 'pages#contact'
  get 'cred', to: 'pages#credentials', as: 'creds'
  get 'tech-news', to: 'pages#tech_news', as: 'tech_news'

  # Set up routes for comments websocket
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p class="app-footer"><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">John Arnold</h3>
    <nav class="nav nav-masthead justify-content-center app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper('nav-link') %>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<div class="container">
  <footer class="blog-footer">
    <p><%= copyright_generator %></p>
    <p>
      <a href="#">Back to top</a>
    </p>
  </footer>
</div>

app/views/shared/_blog_masthead.html.erb
<div class="col-12">
  <h2>John Arnold's Blog</h2>
  <p>An example blog template built with bootstrap.</p>
  <span><%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %></span>
  <span><%= link_to 'Topics', topics_path %></span>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-faded blog-nav">
  <div class="container">
    <%= link_to 'John Arnold', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= nav_helper 'nav-link', 'li' %>
        <%= login_helper 'nav-link' %>
      </ul>
    </div>
  </div>

</nav>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">
      John Arnold is a software engineer and designer specializing in full-stack web applications development.
    </p>
  </div>

  <%= source_helper('alert alert-primary blog-alert') %>

  <div class="p-3">
    <h4 class="font-italic">Topics</h4>
    <% @sidebar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>

  <div class="p-3">
    <h4 class="font-italic">Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://bitbucket.org/jdac" target="_blank"><%= fa_icon "bitbucket-square" %></a></li>
      <li><a href="https://bitbucket.org/jdac" target="_blank"><%= fa_icon "github-square" %></a></li>
      <li><a href="https://twitter.com/drive_jcs" target="_blank"><%= fa_icon "twitter-square" %></a></li>
      <li><a href="https://facebook.com/JdacSolutions" target="_blank"><%= fa_icon "facebook-square" %></a></li>
    </ol>
  </div>
</aside>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About Me", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View all portfolio items", portfolios_path %> |
      <a href="#">Back to top</a>
    </p>
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
    <p>
      <%= link_to 'Learn more about me', about_me_path, class: 'btn btn-primary' %>
      <%= link_to 'Blog', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">
            Add some information about the album below, the author, or any other background context. Make it a few
            sentences long so folks can pick up some informative tidbits. Then, link them off to some social
            networking sites or contact information.
          </p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= nav_helper 'text-white', 'li' %>
            <li><%= login_helper('text-white') %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <strong>John Arnold</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>